{
	"Target": {
		"Path": "/dtdcmobileapp/Rules/getUrlsByClientData.js",
		"RequestProperties": {
			"Headers": {
				"Content-Type": "application/json"
			},
			"Method": "POST"
		},
		"Service": "/dtdcmobileapp/Services/testDestURL.service"
	},
	"_Type": "Action.Type.RestService.SendRequest"
}